image: maven:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: ""

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - target/
    - .m2/

build:
  stage: build
  script:
    - mvn validate
    - mvn compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS clean validate org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' target/site/jacoco/jacoco.csv
  artifacts:
    paths:
      - target/site/jacoco/jacoco.xml
      - target/site/jacoco/

pages:
  stage: deploy
  script:
    - mv target/site/jacoco/ public/
  needs: ["test"]
  dependencies:
    - test
  artifacts:
    paths:
      - public

coverage:
  stage: deploy
  image: haynes/jacoco2cobertura:1.0.4
  script:
    - 'python /opt/cover2cover.py target/site/jacoco/jacoco.xml src/main/java > target/site/cobertura.xml'
    - 'python /opt/source2filename.py target/site/cobertura.xml'
  needs: ["test"]
  dependencies:
    - test
  artifacts:
    reports:
      cobertura: target/site/cobertura.xml

